service: serverless-email-subscription-service
frameworkVersion: '3'

package:
  excludeDevDependencies: true

custom:
  tableName: 'users-table-${sls:stage}'
  region: ${self:provider.region}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  profile: serverless-admin
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action: SNS:Publish
          Resource: !Ref QuotesMessages      
        - Effect: Allow
          Action: "s3:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}
    REGION: ${self:provider.region}
    SNS_TOPIC_ARN: arn:aws:sns:us-east-1:915494082450:quotes-messages-dev
    SENDGRID_API_KEY: "SG.add_your_sendgrid_api_key.ak-TofaGlzex-xxxx"

functions:
  quotes:
    handler: handlers/getQuotes.getQuotes
    events:
      - http:
          path: quotes
          method: get 
          cors: true
  
  subscribe:
    handler: handlers/subscribeUser.subscribeUser
    events:
      - http:
          path: subscribe
          method: post 
          cors: true

  subscribers:
    handler: handlers/getSubscribers.getSubscribers
    events:
      - http:
          path: subscribers
          method: get 
          cors: true

  staticMailer:
    handler: handlers/staticMailer.staticMailer
    events:
      - http:
          path: static-mailer
          method: post
          cors: true

  sendEmail:
    handler: handlers/sendEmail.sendEmail
    events:
      - http:
          path: sendEmail
          method: post
          cors: true
      #Fire at 1 PM every day UTC (9 am EST) - cron examples: https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm
      #https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
      - schedule: cron(0 13 * * ? *)

resources:
  Resources:
    #SNS
    QuotesMessages:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: quotes-messages-${self:provider.stage}
    QuotesMessagesSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref QuotesMessages
        Protocol: email
        Endpoint: your-authorised-email@gmail.com
        DeliveryPolicy: 
          healthyRetryPolicy:
            numRetries: 20
            minDelayTarget: 30
            maxDelayTarget: 600
            backoffFunction: exponential

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
